- name: Sample Cisco playbook
  hosts: cisco
  gather_facts: true
  connection: network_cli
  # Read Username and Password from prompta
  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"
  # Prompt Username and Password
  vars_prompt:
    - name: username
      prompt: User
      private: false

    - name: password
      prompt: Password

  tasks:
    # Run commands on Cisco Router
    - name: Gather Cisco facts
      cisco.ios.ios_command:
        commands:
          - show version
          - show interfaces
      register: out
    # Print commands output
    - name: Print a message
      ansible.builtin.debug:
        msg: "{{ out.stdout[0] }}"
